### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by ferninatorcom** [TangSteven/InstagramBots#1]
Hi! Please excuse my lack of knowledge here. How is one supposed to set this up? Just running it into the browser's console? Or run the script you want with node? (i.e.: node instaLikes.js) I would gladly write documentation if you walk me through. Thanks!

**Comment by steventango** [comment]
I should have included documentation for that, but hopefully this can help you get started, you need to install a userscript manager, for example [Tampermonkey](https://www.tampermonkey.net/), and add the following scripts to Tampermonkey. I will write more documentation tomorrow.
